"""程式化生成 ForgeUE fixture payload 中的 4 个文件(PNG×2 + WAV + JSON)。

FBX 和 MP4 不在本脚本范围,需要手动放置(见 plan Task 1.5/1.6)。
"""
from __future__ import annotations

import json
import struct
import wave
import zlib
from pathlib import Path

PAYLOAD_DIR = Path(__file__).resolve().parents[1] / "fixtures" / "forgeue_manifest" / "payload"


def _write_solid_png(path: Path, width: int, height: int, rgba: tuple[int, int, int, int]) -> None:
    """写一张纯色 RGBA PNG(最简编码,不用 PIL)。"""
    sig = b"\x89PNG\r\n\x1a\n"
    ihdr_data = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    ihdr = _png_chunk(b"IHDR", ihdr_data)
    raw = b""
    row = bytes(rgba) * width
    for _ in range(height):
        raw += b"\x00" + row
    idat = _png_chunk(b"IDAT", zlib.compress(raw, 9))
    iend = _png_chunk(b"IEND", b"")
    path.write_bytes(sig + ihdr + idat + iend)


def _png_chunk(tag: bytes, data: bytes) -> bytes:
    """构造一个 PNG chunk(长度 + tag + data + CRC)。"""
    length = struct.pack(">I", len(data))
    crc = struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    return length + tag + data + crc


def _write_silent_wav(path: Path, seconds: float, sample_rate: int = 16000) -> None:
    """写一段静音 mono 16-bit WAV(用内置 wave 模块,不需 numpy)。"""
    n_frames = int(seconds * sample_rate)
    with wave.open(str(path), "wb") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(sample_rate)
        wav.writeframes(b"\x00\x00" * n_frames)


def _write_material_simple(path: Path) -> None:
    """最简 PBR 五字段 material.definition(spec §3.4 Option α)。

    FU-03: normal_texture_ref 从 None 改为 UE asset path,指向已 import 的 normal map 贴图。
    该贴图由 ae_run_p4_full_texture_normal entry 产出,必须在 material import 前已完成导入。
    """
    payload = {
        "base_color_rgba": [0.5, 0.5, 0.5, 1.0],
        "metallic": 0.0,
        "roughness": 0.7,
        # FU-03: 引用同 run 下 normal map Texture2D 的 UE asset path(不含扩展名)
        "normal_texture_ref": "/Game/Generated/Tavern/run_p4_full/T_run_p4_full_tex_normal",
        "emissive_color_rgba": [0.0, 0.0, 0.0, 1.0],
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def _write_simple_obj_cube(path: Path) -> None:
    """写一个最简 Wavefront OBJ 格式 cube(8 顶点 + 6 面四边形)。

    UE 5.5 AssetTools.ObjFactory 可解析此格式,导入为 StaticMesh。
    """
    obj_text = """# Simple cube generated by generate_forgeue_fixture_payload.py
o ForgeUECube
v -1.0 -1.0 -1.0
v -1.0 -1.0  1.0
v -1.0  1.0 -1.0
v -1.0  1.0  1.0
v  1.0 -1.0 -1.0
v  1.0 -1.0  1.0
v  1.0  1.0 -1.0
v  1.0  1.0  1.0

# 顶点法线
vn -1.0  0.0  0.0
vn  1.0  0.0  0.0
vn  0.0 -1.0  0.0
vn  0.0  1.0  0.0
vn  0.0  0.0 -1.0
vn  0.0  0.0  1.0

# 6 个四边形面(每面共享法线)
f 1//1 3//1 4//1 2//1
f 5//2 6//2 8//2 7//2
f 1//3 5//3 7//3 3//3
f 2//4 4//4 8//4 6//4
f 1//5 2//5 6//5 5//5
f 3//6 7//6 8//6 4//6
"""
    path.write_text(obj_text, encoding="utf-8")


def main() -> None:
    """主入口:依次生成 PNG×3 + WAV + JSON + OBJ 六个 fixture 文件。

    FU-03 新增 tex_normal.png:64×64 RGBA(128,128,255,255) normal map "向上"标准色。
    该贴图对应 manifest entry ae_run_p4_full_texture_normal,
    必须比 material entry 先 import 以便 _creator_path_material 的 load_asset 能命中。
    FU-04 新增 mesh_cube_obj.obj:最简 Wavefront OBJ cube,用于 OBJ static_mesh 真机路径实测。
    """
    PAYLOAD_DIR.mkdir(parents=True, exist_ok=True)
    _write_solid_png(PAYLOAD_DIR / "tex_albedo.png", 64, 64, (128, 128, 128, 255))
    _write_solid_png(PAYLOAD_DIR / "tex_sprite_sheet.png", 128, 128, (255, 255, 255, 255))
    # FU-03: normal map "向上"颜色 RGBA(128,128,255,255),对应 XY=0.5,Z=1.0 法线方向
    _write_solid_png(PAYLOAD_DIR / "tex_normal.png", 64, 64, (128, 128, 255, 255))
    _write_silent_wav(PAYLOAD_DIR / "sfx_click.wav", 0.5)
    _write_material_simple(PAYLOAD_DIR / "material_simple.json")
    # FU-04: 最简 OBJ cube(8 顶点 + 6 法线 + 6 四边形面),程式化 ASCII 生成
    _write_simple_obj_cube(PAYLOAD_DIR / "mesh_cube_obj.obj")
    print(f"[generate_forgeue_fixture_payload] 6 files written under {PAYLOAD_DIR}")  # 5 → 6


if __name__ == "__main__":
    main()
